// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFqh3Fxi72A4deAX2pOma2UR15r4MnTI4',
    appId: '1:1004105871009:web:34580dfc6327525b81cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    authDomain: 'avivamiento-app-ef433.firebaseapp.com',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
    measurementId: 'G-LBVN4FR7JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhU77JHNhEU0vhynsyteG54wYppp1G48',
    appId: '1:1004105871009:android:5189aa58c009d9d081cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJX6dIhRm_Qe8z0diGSxCfCZk5IPjM8oI',
    appId: '1:1004105871009:ios:f4e7c6563b14a8e681cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
    androidClientId: '1004105871009-fhono8b47p8o65rlkjhjb8a0r27f6iid.apps.googleusercontent.com',
    iosClientId: '1004105871009-7skmjra04tonk8ep6erkgqqd5sq95c97.apps.googleusercontent.com',
    iosBundleId: 'com.example.avivamientoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJX6dIhRm_Qe8z0diGSxCfCZk5IPjM8oI',
    appId: '1:1004105871009:ios:f4e7c6563b14a8e681cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
    androidClientId: '1004105871009-fhono8b47p8o65rlkjhjb8a0r27f6iid.apps.googleusercontent.com',
    iosClientId: '1004105871009-7skmjra04tonk8ep6erkgqqd5sq95c97.apps.googleusercontent.com',
    iosBundleId: 'com.example.avivamientoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNcdXznvBdf22lPsizRyHkXoJ3hJvcDfo',
    appId: '1:1004105871009:web:c3c8102acbdb82a681cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    authDomain: 'avivamiento-app-ef433.firebaseapp.com',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
    measurementId: 'G-4QP1D2YNY2',
  );

}