// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_tdeDSXWMvhZ7SsY6XoHf8awdsqzOMb8',
    appId: '1:1004105871009:web:34580dfc6327525b81cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    authDomain: 'avivamiento-app-ef433.firebaseapp.com',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
    measurementId: 'G-LBVN4FR7JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1hcGuCIPZhyzoCDm8cusdMV2pDEBMjAs',
    appId: '1:1004105871009:android:5189aa58c009d9d081cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0SafDsFozX9MWHmaJTU-bujwXyjxu7iY',
    appId: '1:1004105871009:ios:f4e7c6563b14a8e681cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
    iosBundleId: 'com.example.avivamientoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0SafDsFozX9MWHmaJTU-bujwXyjxu7iY',
    appId: '1:1004105871009:ios:f4e7c6563b14a8e681cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
    iosBundleId: 'com.example.avivamientoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_tdeDSXWMvhZ7SsY6XoHf8awdsqzOMb8',
    appId: '1:1004105871009:web:c3c8102acbdb82a681cae0',
    messagingSenderId: '1004105871009',
    projectId: 'avivamiento-app-ef433',
    authDomain: 'avivamiento-app-ef433.firebaseapp.com',
    storageBucket: 'avivamiento-app-ef433.firebasestorage.app',
    measurementId: 'G-4QP1D2YNY2',
  );
}
